python train_fairAC_GNN_report.py \
        --seed=42 \
        --epochs=3000 \
        --model=GCN \
        --dataset=nba \
        --num-hidden=128 \
        --acc=0.70 \
        --roc=0.72 \
        --lambda1=1.0 \
        --lambda2=0.7   \
        --label_number=1000  \
        --feat_drop_rate=0.3
